spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/api/profiles/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/carts/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
        - id: wallet-service
          uri: lb://wallet-service
          predicates:
            - Path=/api/wallets/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/api/delivery/**
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/reviews/**
        - id: wishlist-service
          uri: lb://wishlist-service
          predicates:
            - Path=/api/wishlist/**
        - id: coupon-service
          uri: lb://coupon-service
          predicates:
            - Path=/api/coupons/**
        - id: website-controller
          uri: lb://website-controller
          predicates:
            - Path=/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 3
server:
  port: 8080
