server.port=8086
spring.application.name=website-controller

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# GitHub OAuth2 Configuration
spring.security.oauth2.client.registration.github.client-id=Iv23lipD5XvN7ZEM6FvA
spring.security.oauth2.client.registration.github.client-secret=735f11eb11b5eeb55787d55986968ecab487f7b3
